name: Pull Request

on:
  pull_request:
    branches:
      - "master"
      - "release"

jobs:
  build-and-upload:
    uses: ./.github/workflows/build_and_upload.yml
    with:
      isRelease: false
      shouldUpload: false
    secrets: inherit